-- this syntax is used for testing the INSERT with OVERRIDING {SYSTEM|USER} 

VALUE feature in SAP HANA

CREATE COLUMN TABLE DEVTEST.BOARDMEMBERS 
(
BMID INTEGER,
BM VARCHAR(20),
ROLE VARCHAR(20),
SALARY INTEGER
);

INSERT INTO BOARDMEMBERS VALUES (1, 'Bob', 'CEO', 1500000);
INSERT INTO BOARDMEMBERS VALUES (2, 'Denys', 'CTO', 1000000);



CREATE COLUMN TABLE DEVTEST.EMPLOYEES 
(
EMPID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 100),
EMP VARCHAR(20),
ROLE VARCHAR(20),
SALARY INTEGER
);

INSERT INTO DEVTEST.EMPLOYEES VALUES('Christiano','Manager',500000);
INSERT INTO DEVTEST.EMPLOYEES VALUES('Eric','Manager',350000);
INSERT INTO DEVTEST.EMPLOYEES VALUES('Ryan','Director',450000);
INSERT INTO DEVTEST.EMPLOYEES VALUES('Bryan','Director',150000);
INSERT INTO DEVTEST.EMPLOYEES VALUES('Doreen','Manager',500000);
INSERT INTO DEVTEST.EMPLOYEES VALUES('Gabriel','Manager',350000);
INSERT INTO DEVTEST.EMPLOYEES VALUES('Angel','Director',450000);
INSERT INTO DEVTEST.EMPLOYEES VALUES('Robin','Director',150000);
INSERT INTO DEVTEST.EMPLOYEES VALUES('Sarah','Manager',500000);
INSERT INTO DEVTEST.EMPLOYEES VALUES('Peter','Manager',350000);

SELECT * FROM EMPLOYEES;


INSERT INTO EMPLOYEES (SELECT * FROM BOARDMEMBERS WHERE BMID = 2);

INSERT INTO EMPLOYEES (SELECT BM, ROLE, SALARY FROM BOARDMEMBERS WHERE BMID = 2);
SELECT * FROM EMPLOYEES;


INSERT INTO EMPLOYEES OVERRIDING SYSTEM VALUE (SELECT * FROM BOARDMEMBERS WHERE BMID = 1);
SELECT * FROM EMPLOYEES;
